version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: prisma
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: price-tracker
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - './db/data:/var/lib/postgres/data'
      - './db/init:/docker-entrypoint-initdb.d'